name: Update Number

on:
  schedule:
    - cron: "0 6 * * *"  
  workflow_dispatch:     

jobs:
  update_number:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.0  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run the update script
        run: |
          python update_number.py

      - name: Commit changes
        run: |
          git config user.name "Sergey Funtikov"  
          git config user.email "sfuntikoff@gmail.com"  
          git add number.txt
          git commit -m "Update number automatically"
          git push https://${{ secrets.GH_TOKEN }}@github.com/Funt1koff/fancy_profile.git HEAD:main
